[server]
# Setting the headless mode to true, useful for deployment
headless = true

# Port setting (default is 8501)
port = 8501

# Address where to listen for requests (default is localhost)
address = "0.0.0.0"

# Enable CORS protection
enableCORS = false

# If you want to hide Streamlit's "Made with Streamlit" watermark
showServerInformation = false

[theme]
# Primary accent for interactive elements
primaryColor = "#1f77b4"

# Background color for the main content area
backgroundColor = "#ffffff"

# Background color for the sidebar and the header
secondaryBackgroundColor = "#f0f2f6"

# Text color
textColor = "#31333f"

# Font family for the app (sans-serif, serif, monospace)
font = "sans serif"

[logger]
# Sets the logger level to debug (default is info)
level = "info"
